wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709563965.22501
    t:
      1:
      - 1
      - 41
      - 49
      - 51
      - 55
      - 63
      2:
      - 1
      - 41
      - 49
      - 51
      - 55
      - 63
      3:
      - 17
      - 23
      - 37
      4: 3.8.18
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
batch_size:
  desc: null
  value: 48
epochs:
  desc: null
  value: 300
huber_a:
  desc: null
  value: 0.2
loss_type:
  desc: null
  value: huber
num_iter_kirwls:
  desc: null
  value: 1
outlier_fraction:
  desc: null
  value: 0.1
num_blocks:
  desc: null
  value: 5
model:
  desc: null
  value: deit_tiny_patch16_224
input_size:
  desc: null
  value: 224
drop:
  desc: null
  value: 0.0
drop_path:
  desc: null
  value: 0.1
model_ema:
  desc: null
  value: true
model_ema_decay:
  desc: null
  value: 0.99996
model_ema_force_cpu:
  desc: null
  value: false
opt:
  desc: null
  value: adamw
opt_eps:
  desc: null
  value: 1.0e-08
opt_betas:
  desc: null
  value: null
clip_grad:
  desc: null
  value: null
momentum:
  desc: null
  value: 0.9
weight_decay:
  desc: null
  value: 0.05
sched:
  desc: null
  value: cosine
lr:
  desc: null
  value: 0.0005
lr_noise:
  desc: null
  value: null
lr_noise_pct:
  desc: null
  value: 0.67
lr_noise_std:
  desc: null
  value: 1.0
warmup_lr:
  desc: null
  value: 1.0e-06
min_lr:
  desc: null
  value: 1.0e-05
decay_epochs:
  desc: null
  value: 30
warmup_epochs:
  desc: null
  value: 5
cooldown_epochs:
  desc: null
  value: 10
patience_epochs:
  desc: null
  value: 10
decay_rate:
  desc: null
  value: 0.1
color_jitter:
  desc: null
  value: 0.4
aa:
  desc: null
  value: rand-m9-mstd0.5-inc1
smoothing:
  desc: null
  value: 0.1
train_interpolation:
  desc: null
  value: bicubic
repeated_aug:
  desc: null
  value: true
reprob:
  desc: null
  value: 0.25
remode:
  desc: null
  value: pixel
recount:
  desc: null
  value: 1
resplit:
  desc: null
  value: false
mixup:
  desc: null
  value: 0.8
cutmix:
  desc: null
  value: 1.0
cutmix_minmax:
  desc: null
  value: null
mixup_prob:
  desc: null
  value: 1.0
mixup_switch_prob:
  desc: null
  value: 0.5
mixup_mode:
  desc: null
  value: batch
teacher_model:
  desc: null
  value: regnety_160
teacher_path:
  desc: null
  value: ''
distillation_type:
  desc: null
  value: none
distillation_alpha:
  desc: null
  value: 0.5
distillation_tau:
  desc: null
  value: 1.0
finetune:
  desc: null
  value: /home/ubuntu/Kpca/checkpoints/rpc/sym_baseline.pth
data_path:
  desc: null
  value: /vinai/tannhm/imagenet/
data_set:
  desc: null
  value: IMNET
inat_category:
  desc: null
  value: name
attack:
  desc: null
  value: cw
eps:
  desc: null
  value: 0.00784313725490196
output_dir:
  desc: null
  value: /home/ubuntu/Kpca/checkpoints/
device:
  desc: null
  value: cuda
seed:
  desc: null
  value: 0
resume:
  desc: null
  value: ''
start_epoch:
  desc: null
  value: 0
eval:
  desc: null
  value: '1'
inc_path:
  desc: null
  value: null
dist_eval:
  desc: null
  value: false
num_workers:
  desc: null
  value: 10
pin_mem:
  desc: null
  value: true
world_size:
  desc: null
  value: 1
dist_url:
  desc: null
  value: env://
use_wandb:
  desc: null
  value: '1'
project_name:
  desc: null
  value: robust_attack
job_name:
  desc: null
  value: sym_baseline_cw
kernel_size:
  desc: null
  value: null
stride:
  desc: null
  value: null
robust:
  desc: null
  value: false
